---
title: "FAQ Laboratorio di statistica"
output: 
        github_document:
                toc: TRUE
                # toc_depth: 3 # default = 3
                # fig_width: 7 # default = 7
                # fig_height: 5 # default = 5
---

```{r setup, include=FALSE}
# knitr::opts_chunk$set(echo = TRUE)
```

## Come ottenere i crediti:

#### È obbligatorio frequentare il corso?

Sì, si chiama frequenza proficua per un motivo. È obbligatorio seguire almeno l'80% delle lezioni.

#### Si possono recuperare le lezioni perse?

Sì, direi di sì, *magari* a gruppi, *magari* non un mese dopo.

#### Quante sono le ore di corso?

Sono 24 ore di laboratorio e 47 di studio individuale.

#### Si svolgeranno delle prove intermedie durante il corso?

Ci saranno piccoli incarichi di lezione in lezione, e verranno portati avanti progetti individuali o di gruppo durante il corso, ma nessuna prova formale.

#### In cosa consisterà la prova finale esattamente?

Essendo il primo anno il formato della prova finale non è _esattamente_ definito.  
L'idea è di farvi utilizzare in un'analisi organica tutti i piccoli compiti che vi vengono assegnati durante il corso.


## Domande tecniche:

#### L'installazione di GIT per Windows sconsiglia di usare VIM come editor di default, che faccio?

Non ho consigli specifici, se qualcuno ne ha è il benvenuto, ma penso che provate le nuve GUI che installerete (io ho consigliato GitHub Desktop, ma non è l'unica), userete solo quelle per gestire il vostro GIT.

#### Esiste un numero massimo di account che possono contribuire alla realizzazione dello stesso progetto?

No, uno degli scopi di GitHub è quello di permettere una collaborazione diffusa, se si prevede l'accesso di numerosi utenti è buona regola stabilire delle norme di comportamento, come indicato nelle guide di GitHub stesso.

#### Come si crea una **pull request**

Il punto di chiedervelo prima di spiegarvelo è di imparare a cercare le risposte sul web.  
La raccomandazione è cercare in inglese.

#### E' possibile lavorare offline su GitHub desktop?

Si, di fatto è uno dei principali vantaggi. Chiaramente non può sincronizzarsi con la repository on-line.
Qui di si possono fare le **commit** regolari, che verranno in seguito sincronizzate (salvando tutto lo storico del progetto).

#### Dove posso trovare i tutorial per l'utilizzo di GitHub? (_GitHub for dummies_)

Io partirei proprio dalle [guide di GitHub](https://guides.github.com/activities/hello-world/).
Speriamo che qualcosa di ancora più amichevole siate in grado di produrlo voi.

#### Che differenza c'è tra Branch e Fork?

* Fork è una copia di una _repository_, contiene **tutte** le branches della repository originale.
* Branch è una copia della _master branch_, fatta per poter lavorare senza incasinare il lavoro degli altri.

#### Come si crea una pull request da GitHub Dekstop

Non si può: il comando _Create pull request_ dalla branch nella **propria fork**, reindirizza alla pagina giusta sul browser.

#### Come si caricano i dati su Rstudio

Per caricare i dati su RStudio occorre averli già su un file, che sia un documento on-line, un file di testo o un foglio Excel, vedremo di fare un tutorial apposito su questo argomento.

#### Come faccio a mostrare i risultati nel mio tutorial? Quando faccio *Knit to html/word/pdf* su R va tutto bene ma qui su github si vedono soltanto le linee di comando. E poi, qual'è la differenza tra il formato *md* e *rmd*? Per cosa si deve usare uno e per cosa l'altro? 

[Link al tutorial](https://github.com/saveriofrancini/My_first_function)

Noi prenderemo l'abitudine di scrivere tutto in **.rmd**, le differenze sono fondamentalmente nella possibilità di eseguire i comandi che si scrivono e generare i risultati e i grafici, senza doverli incollare come riferimenti esterni.
Se controllate l'intestazione di questo file noterete che l'output non è un html, perché le mie intenzioni sono di tenerlo su GitHub, che ha un bel modo di visualizzare i file **.md**, quindi io scrivo il file su RStudio come **.rmd**, il pulsante con la palla di filo blu in alto a sinistra usa automaticamente l'opzione di default che ho messo nell'intestazione del file (*github_document:*).
Il fatto che il file si chiami **README.rmd**, e quindi generi un **README.md**, lo fa aprire direttamente sulla pagina di GitHub.
Per questo è bene che non si lavori mai sul file **.md** se c'è un **.rmd** che lo genera, perché quando verrà generato di nuovo tutte le modifiche andranno perse.

## Altre domande:

#### Per l'esame di stato da Agronomo Forestale è necessaria la conoscenza di R?

No, al momento credo l'unico software chiesto all'esame _**credo**_ siano i CAD.

#### I compiti vanno scritti su Rstudio e poi caricati in una repo su GitHub o si puo scrivere direttamente su GitHub?

Di fatto è più comodo scrivere direttamente su RStudio, anche se non c'è codice da eseguire, in modo da utilizzare solo la sintassi del formato **RMarkdown**, che poi sarà trasformato in **markdown** da RStudio.

#### Mi può mandare il modellino per la delibera dei crediti?

Questa si che è una domanda complessa... sentirò in segreteria!!!

## Riferimenti e tutorials:

#### È disponibile una guida online a cui fare riferimento per il linguaggio R?

Si, fra le ufficiali la base di riferimento è [RStudio.com](https://www.rstudio.com/online-learning/)

#### Finito il corso, possiamo trovare sul web qualche valido tutorial per migliorare le proprie capacità nell'uso di R? Ne consigliereste qualcuno in particolare?

Insieme al materiale delle lezioni verrà fornito anche il materiale di approfondimanto, la community di R è estremamente vivace, e il miglior modo di entrare nel vivo della materia è quello di seguirne gli attori principali. Seguire i collegamenti nel materiale allegato dovrebbe portare a quasi tutte le persone giuste.

#### Ho trovato questo tutorial in pdf, [Robinson icebreakerR](https://cran.r-project.org/doc/contrib/Robinson-icebreaker.pdf), secondo te va bene?

Direi di si, prende le cose parecchio di petto, quindi può volerci un po' di pazienza, magari è un po' complesso per chi parte proprio da zero.

---

<div align="center">
[Syllabus](../README.md)
</div>
---

